### ISSUE TITLE
Git bash `lh arch` fails overwriting a bucket history file

### ISSUE THREAD

**Issue by Stabledog** [sanekits/localhist#5]
Seems like `os.rename()` can't rename if target exists, but only on the Windows version?
```
Traceback (most recent call last):
  File "C:\Users\lmatheson4\.local\bin\localhist\bash_history_tool.py", line 402, in <module>
    write_farm(ctx.archive_dir, farm)
  File "C:\Users\lmatheson4\.local\bin\localhist\bash_history_tool.py", line 360, in write_farm
    result += write_bucket(
  File "C:\Users\lmatheson4\.local\bin\localhist\bash_history_tool.py", line 347, in write_bucket
    os.rename(tmpname, dest_file)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\lmatheson4\\.localhist-archive\\PW0202FD-gitbash\\2022-08\\bash_history.238' -> 'C:\\Users\\lmatheson4\\.localhist-archive\\PW0202FD-gitbash\\2022-08\\bash_history'
ERROR(localhist-archive.sh): 
```

**Comment by Stabledog** [comment]
Fixed in 2.3.1
